from . import res_company
from . import res_config_settings
from . import employee_loan_stage
from . import employee_loan_type
from . import employee_loan
from . import employee_loan_installment_line
from . import employee_loan_guarantor
from . import employee_loan_manually_settlement
from . import employee_loan_installment_skip
from . import hr_salary_rule