{
	'name': 'Local Tax Configuration',
	'version': '16.0.0.1',
	'sequence': 1,
	'summary': 'Local Tax Configuration',
	'author': 'Centrics Business Solutions',
	'maintainer': 'Centrics Business Solutions',
	'company': 'Centrics Business Solutions',
	'website': 'http://www.centrics.cloud/',
	'depends': ['sale', 'account'],
	'data': [
		'views/account_journal_views.xml',
		'views/account_move_views.xml',
		'views/account_tax_views.xml',
		'views/res_company_views.xml',
		'views/res_partner_views.xml',
		'views/sale_order_views.xml',
	],
	'images': [],
	'license': 'AGPL-3',
	'installable': True,
	'application': True,
	'auto_install': False,
}
