{
    'name': 'Petty Cash',
    'version': '16.0.0.1',
    'license': 'LGPL-3',
    'sequence': 1,
    'author': 'Centrics Business Solutions PVT Ltd',
    'company': 'Centrics Business Solutions PVT Ltd',
    'website': 'http://www.centrics.cloud/',
    'summary': 'Manage process of Petty cash',
    'description': """Manage process of Petty cash""",
    'depends': ['base', 'utm', 'account', 'account_accountant', 'hr'],
    'data': [
        'data/mail_template.xml',
        'data/ir_sequence.xml',

        'reports/paperformat.xml',
        # 'reports/cash_out_payment_voucher.xml',
        'reports/reimbursement_payment_voucher.xml',
        'reports/petty_cash_topup_payment_voucher.xml',
        'reports/petty_cash_iou_petty_cash_voucher.xml',

        'reports/cheque/paperformat.xml',
        'reports/cheque/amana_cheque_layout_topup.xml',
        'reports/cheque/amana_cheque_layout_iou_request.xml',
        'reports/cheque/amana_cheque_layout_reimbursement.xml',
        'reports/cheque/commercial_cheque_layout_topup.xml',
        'reports/cheque/commercial_cheque_layout_iou_request.xml',
        'reports/cheque/commercial_cheque_layout_reimbursement.xml',
        'reports/cheque/ndb_cheque_layout_topup.xml',
        'reports/cheque/ndb_cheque_layout_reimbursement.xml',
        'reports/cheque/ndb_cheque_layout_iou_request.xml',
        'reports/cheque/seylan_cheque_layout_topup.xml',
        'reports/cheque/seylan_cheque_layout_iou_request.xml',
        'reports/cheque/seylan_cheque_layout_iou_reimbursement.xml',

        'security/security.xml',
        'security/access_rules.xml',
        'security/ir.model.access.csv',

        'wizard/reject_reason_view.xml',
        'wizard/increase_cash_float_wizard_views.xml',

        'views/res_config_settings_view.xml',
        'views/petty_cash_views.xml',
        'views/reimbursements_views.xml',
        'views/petty_cash_topup_views.xml',
        'views/petty_cash_reason_view.xml',
        'views/iou_request_views.xml',
        'views/account_journal_view.xml',
        'views/hr_employee_view.xml',
        'views/account_move.xml',
        'views/cash_drawer_summery.xml',
        'views/reimbursment_summary_report_view.xml',
        'views/menuitem.xml',

        'wizard/approve_user_view.xml',
        'wizard/approved_with_coment_wizard_view.xml',
        'wizard/petty_cash_balance_wizard_view.xml',
        'wizard/multi_reimbursement_request_approval_view.xml',
        'wizard/multi_cash_out_approval_view.xml',
        'wizard/expenses_report_wizard_view.xml',
        'wizard/add_vendor_bills_to_iou_wizard_view.xml',
        'wizard/iou_confirmation_wizard_views.xml',


    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
