from . import res_company
from . import res_config_settings
from . import hr_contract
from . import hr_attendance
from . import hr_overtime_rule
from . import hr_overtime_template
from . import hr_overtime_pre_approval
from . import buffer_time_configuration
from . import overtime_dynamic_deduction